// lib/strings.ts
// Every user-facing string lives here, in English. Keeping copy in one place
// keeps the tone consistent and makes a future translation a single file.

export const str = {
  app: {
    name: "repiq",
    description: "Minimalist workout tracker",
  },
  common: {
    save: "Save",
    saving: "Saving…",
    cancel: "Cancel",
    back: "Back",
    close: "Close",
    next: "Next",
    continue: "Continue",
    delete: "Delete",
    edit: "Edit",
    on: "On",
    off: "Off",
    rest: "Rest",
    genericError: "Something went wrong. Please try again.",
  },
  nav: {
    label: "Main navigation",
    dashboard: "Dashboard",
    schedule: "Schedule",
    statistics: "Statistics",
    account: "Account",
  },
  dashboard: {
    title: "Dashboard",
    today: (day: string) => `Today · ${day}`,
    finished: "Finished",
    finishedHint: "Workout completed today",
    startAnother: "Start another session",
    resume: "Resume workout",
    exercisesScheduled: (n: number) => `${n} ${n === 1 ? "exercise" : "exercises"} scheduled`,
    restDay: "Rest Day",
    nothingScheduled: "Nothing scheduled",
    weight: "Weight",
    completed: "Completed",
    workouts: "workouts",
  },
  reminders: {
    title: "You have a workout planned today",
    body: (name: string, count: number) =>
      `${name} · ${count} ${count === 1 ? "exercise" : "exercises"}. Time to train!`,
  },
  schedule: {
    title: "Schedule",
    week: "Week Schedule",
    weekMeta: "Tap a day to change",
    selectFor: (day: string) => `Choose plan for ${day}`,
    plans: "Workout Plans",
    plansMeta: "templates",
    noPlans: "No plans yet",
    addPlan: "Add Plan",
    newPlanPlaceholder: "e.g. Upper Body",
    planTitle: "Plan title",
  },
  plan: {
    badge: "Plan",
    name: "Plan Name",
    nameMeta: "tap to edit",
    exercises: "Exercises",
    total: (n: number) => `${n} total`,
    addExercise: "Add Exercise",
    deletePlan: "Delete Plan",
    confirmDeletePlan: "Tap again to delete",
    chooseExercise: "Choose Exercise",
    newExercise: "+ New Exercise",
    customExercise: "Custom Exercise",
    exerciseNamePlaceholder: "Exercise name (e.g. Incline Bench)",
    backToSelection: "Back to selection",
    sets: "Sets",
    reps: "Reps",
    rest: "Rest",
    other: "Other…",
    summary: (sets: number, reps: number, rest: string) => `${sets} sets × ${reps} reps · ${rest} rest`,
    invalidInput: "Check the exercise name, sets, reps and rest.",
  },
  workout: {
    set: "Set",
    reps: "Reps",
    done: "Done",
    prev: (value: string) => `Prev: ${value}`,
    progress: (current: number, total: number) => `${current}/${total}`,
    rest: "Rest",
    restAdd: "+15s",
    restSubtract: "−15s",
    restSkip: "Skip",
    restAddLabel: "Add 15 seconds",
    restSubtractLabel: "Remove 15 seconds",
    restSkipLabel: "Skip rest",
    leave: "Leave workout",
    finish: "Finish Workout",
    finishing: "Saving…",
    discard: "Discard workout",
    discardConfirm: "Tap again to discard all sets",
    markSetDone: (n: number) => `Mark set ${n} done`,
    markSetNotDone: (n: number) => `Mark set ${n} not done`,
    weightFor: (n: number, unit: string) => `Set ${n} weight in ${unit}`,
    repsFor: (n: number) => `Set ${n} reps`,
    empty: "This plan has no exercises yet.",
    editPlan: "Edit plan",
    saveSaving: "Saving…",
    saveSaved: "Saved",
    saveOffline: "Offline · will sync",
    saveFailed: "Not saved",
    saveRetry: "Retry",
    unsavedBeforeFinish: "Some sets aren't saved yet. Check your connection and try again.",
    restNotificationTitle: "Rest complete",
    restNotificationBody: "Time for your next set.",
  },
  statistics: {
    title: "Statistics",
    total: "Total",
    workouts: "workouts",
    weight: "Weight",
    tapToLog: (unit: string) => `${unit} · tap to log`,
    logWeight: "Log Today's Weight",
    weightPlaceholder: (unit: string) => (unit === "lbs" ? "e.g. 173" : "e.g. 78.5"),
    activity: "Activity",
    weekdays: ["M", "T", "W", "T", "F", "S", "S"],
    invalidWeight: "Enter a valid weight.",
  },
  account: {
    title: "Account",
    profile: "Athlete Profile",
    details: "Account Details",
    name: "Name",
    age: "Age",
    email: "Email",
    username: "Username",
    detailsSaved: "Account details saved.",
    units: "Units",
    unitsMeta: "weight",
    notifications: "Notifications",
    notificationsMeta: "alerts",
    workoutReminders: "Workout Reminders",
    restTimerAlerts: "Rest Timer Alerts",
    notificationsBlocked: "Notifications are blocked in your browser settings.",
    activity: "Activity Summary",
    completedSessions: "Completed Sessions",
    savedPlans: "Saved Plans",
    currentWeight: "Current Weight",
    password: "Password",
    passwordMeta: "security",
    currentPassword: "Current password",
    newPassword: "New password",
    updatePassword: "Update Password",
    updatingPassword: "Updating…",
    passwordChanged: "Password changed. Other devices were signed out.",
    enterCurrentPassword: "Please enter your current password.",
    enterNewPassword: "Please enter a new password.",
    dataManagement: "Data Management",
    dataMeta: "danger",
    resetHistory: "Reset Workout History",
    resetHistoryConfirm: "Tap again to erase your history",
    signOut: "Sign Out",
    timezone: "Timezone",
  },
  auth: {
    signIn: "Sign In",
    signingIn: "Signing in…",
    createAccount: "Create Account",
    creating: "Creating…",
    athleteProfile: "Athlete Profile",
    notifications: "Notifications",
    step: (n: number, total: number) => `Step ${n} of ${total}`,
    usernameOrEmail: "Username or Email",
    usernameOrEmailPlaceholder: "athlete or athlete@example.com",
    email: "Email",
    emailPlaceholder: "athlete@example.com",
    password: "Password",
    passwordPlaceholder: (min: number) => `At least ${min} characters`,
    fullName: "Full Name",
    fullNamePlaceholder: "Alex Miller",
    username: "Username",
    usernamePlaceholder: "alexm",
    age: "Age",
    workoutReminders: "Workout Reminders",
    workoutRemindersHint: "Morning notification for your daily plan",
    restTimerAlerts: "Rest Timer Alerts",
    restTimerAlertsHint: "Notification when your rest period ends",
    finish: "Finish & Start",
    checking: "Checking…",
    backToSignIn: "Back to Sign In",
    fillAllFields: "Please fill in all fields.",
    enterEmailAndPassword: "Please enter both email and password.",
    enterNameAndUsername: "Please enter your name and username.",
    invalidCredentials: "Invalid username or password.",
    loginFailed: "Couldn't sign in. Please try again.",
    registrationFailed: "Couldn't create your account. Please try again.",
    usernameTooShort: "Username must be at least 3 characters.",
    usernameInvalid: "Use 3–30 lowercase letters, numbers, dots or underscores.",
    usernameTaken: "Username is already taken.",
    usernameCheckFailed: "Couldn't check that username right now. Please try again.",
    enterUsername: "Please enter a username.",
    emailInvalid: "Please enter a valid email address.",
    emailTaken: "Email is already registered.",
    ageInvalid: "Please enter an age between 13 and 120.",
    passwordMismatch: "Current password does not match.",
  },
  pwa: {
    updateAvailable: "A new version of repiq is available.",
    reload: "Reload",
    offline: "You're offline",
  },
} as const;
